const defaultData = [
    "Marry me chicken",
    "Christmas bark",
    "Cucumber salad",
    "Cranberry sauce",
    "Cowboy caviar",
    "Potato soup",
    "Espresso martini",
    "Turkey brine",
    "Ranch water",
    "Gingerbread cookie",
    "Chia pudding",
    "Baked brie",
    "Blueberry muffin",
    "Deviled eggs",
    "Green bean casserole",
    "Corned beef and cabbage",
    "Smashed potatoes",
    "Caesar dressing",
    "Egg bites",
    "Overnight oats",
    "Turkey chili",
    "Swedish meatball",
    "Cinnamon roll",
    "Cosmopolitan",
    "Crockpots",
    "Aperol spritz",
    "Tuna casserole",
    "Pasta salad",
    "Breakfast casseroles",
    "Shortbread cookie",
    "Peach crisp",
    "Crab rangoon",
    "Mashed potatoes",
    "Stuffed peppers",
    "Lentil soup",
    "Peach cobbler",
    "Old fashioned",
    "Chicken cacciatore",
    "Chocolate chip cookie",
    "Zuppa toscana",
    "Lemon bars",
    "Greek salad",
    "Banana pudding",
    "Street corn",
    "Hummingbird nectar",
    "Banana muffin",
    "Stuffed shells",
    "Macaroni salad",
    "Roasted carrots",
    "Chicken chili",

    "Marry me chicken",
    "Christmas bark",
    "Cucumber salad",
    "Cranberry sauce",
    "Cowboy caviar",
    "Potato soup",
    "Espresso martini",
    "Turkey brine",
    "Ranch water",
    "Gingerbread cookie",
    "Chia pudding",
    "Baked brie",
    "Blueberry muffin",
    "Deviled eggs",
    "Green bean casserole",
    "Corned beef and cabbage",
    "Smashed potatoes",
    "Caesar dressing",
    "Egg bites",
    "Overnight oats",
    "Turkey chili",
    "Swedish meatball",
    "Cinnamon roll",
    "Cosmopolitan",
    "Crockpots",
    "Aperol spritz",
    "Tuna casserole",
    "Pasta salad",
    "Breakfast casseroles",
    "Shortbread cookie",
    "Peach crisp",
    "Crab rangoon",
    "Mashed potatoes",
    "Stuffed peppers",
    "Lentil soup",
    "Peach cobbler",
    "Old fashioned",
    "Chicken cacciatore",
    "Chocolate chip cookie",
    "Zuppa toscana",
    "Lemon bars",
    "Greek salad",
    "Banana pudding",
    "Street corn",
    "Hummingbird nectar",
    "Banana muffin",
    "Stuffed shells",
    "Macaroni salad",
    "Roasted carrots",
    "Chicken chili",
];

export default defaultData;